image: node:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

# before_script:
# - npm ci

# build:
#   before_script:
#   - apt-get update
#   - apt-get install -y p7zip-full
#   - npm ci
#   script:
#   - npm run build
#   - cd dist
#   - 7z a -mm=Deflate -mx=9 13thcenturykinght.zip *.html *.js
#   - cd -
#   - mv dist/13thcenturykinght.zip ./
#   # - echo 'file_size $(stat --printf="%s" 13thcenturykinght.zip)' > metrics.txt
#   #- test $(stat --printf="%s" 13thcenturykinght.zip) -lt 13312
#   artifacts:
#     paths:
#     - 13thcenturykinght.zip
#     # reports:
#     #   metrics: metrics.txt

pages:
  script:
  - npm ci
  - npm run build
  - mkdir .public
  - cp dist/index.html .public
  - cp dist/main.js .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
    - main
